import { File, Paths } from 'expo-file-system';
import * as Sharing from 'expo-sharing';

import { formatINR } from '@/lib/money';
import { warrantyExpiryMs } from '@/lib/warranty';
import type { Expense } from '@/types';

/**
 * Self-contained HTML proof-of-purchase for a warranty claim:
 * purchase details table + the receipt photo embedded as base64. Pure.
 */
export function buildClaimHtml(expense: Expense, imageBase64: string | null): string {
  const expiry = warrantyExpiryMs({
    purchaseDateMs: expense.spentAt,
    warrantyMonths: expense.warrantyMonths,
  });
  const rows: [string, string][] = [
    ['Item', expense.itemName ?? '—'],
    ['Merchant', expense.merchant ?? '—'],
    ['Purchase date', new Date(expense.spentAt).toDateString()],
    ['Amount paid', formatINR(expense.amountMinor)],
    ['Warranty', expense.warrantyMonths !== null ? `${expense.warrantyMonths} months` : '—'],
    ['Warranty valid until', expiry !== null ? new Date(expiry).toDateString() : '—'],
  ];
  if (expense.note) rows.push(['Note', expense.note]);

  const detailRows = rows
    .map(([k, v]) => `<tr><th align="left">${escapeHtml(k)}</th><td>${escapeHtml(v)}</td></tr>`)
    .join('\n');
  const image = imageBase64
    ? `<h2>Receipt</h2><img src="data:image/jpeg;base64,${imageBase64}" style="max-width:100%" alt="Receipt" />`
    : '<p><em>No receipt image attached.</em></p>';

  return `<!doctype html>
<html><head><meta charset="utf-8"><title>Warranty claim — ${escapeHtml(expense.itemName ?? 'item')}</title>
<style>body{font-family:monospace;max-width:640px;margin:24px auto;padding:0 12px}th{padding-right:16px}</style>
</head><body>
<h1>Proof of purchase</h1>
<table>${detailRows}</table>
${image}
<p><small>Generated by Warden — data stored on-device only.</small></p>
</body></html>`;
}

/** Write the claim pack to cache and open the system share sheet. */
export async function shareClaimPack(expense: Expense): Promise<void> {
  let imageBase64: string | null = null;
  if (expense.imageUri) {
    try {
      imageBase64 = await new File(expense.imageUri).base64();
    } catch {
      imageBase64 = null; // image missing/unreadable — ship the details anyway
    }
  }

  const html = buildClaimHtml(expense, imageBase64);
  const file = new File(Paths.cache, `warden-claim-${expense.id}.html`);
  file.create({ overwrite: true });
  file.write(html);

  if (!(await Sharing.isAvailableAsync())) return;
  await Sharing.shareAsync(file.uri, {
    mimeType: 'text/html',
    dialogTitle: 'Share claim pack',
  });
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
